dist: trusty
sudo: required
git:
  depth: 1
branches:
  only:
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get -qq install python3-pip
install:
  - pip3 install virtualenv
  - virtualenv travis_env
script:
  - source travis_env/bin/activate
  - pip install -r ./requirements.txt
  - python ./manage.py test
