CONFIRMATION_MSG_FILE = "sms_app/assets/confirmation_msg.txt"
LANG_SELECT_MSG_FILE = "sms_app/assets/language_selection_msg.txt"
SUBSCRIBE_HELP_MSG_FILE = "sms_app/assets/subscribe_help_msg.txt"
UNSUPPORTED_LANG_MSG_FILE = "sms_app/assets/unsupported_lang_msg.txt"
WELCOME_MSG_FILE = "sms_app/assets/welcome_msg.txt"
UNSUBSCRIBED_MSG_FILE = "sms_app/assets/unsubscribed_msg.txt"
ERROR_MSG_FILE = "sms_app/assets/error_msg.txt"
